# Stubs for arrow.constants (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

MAX_TIMESTAMP: float
MAX_TIMESTAMP_MS: Any
MAX_TIMESTAMP_US: Any
