# Stubs for arrow.formatter (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class DateTimeFormatter:
    locale: Any = ...
    def __init__(self, locale: str = ...) -> None: ...
    def format(cls, dt: Any, fmt: Any): ...
